workers: 6
weight_decay: 0.0005
momentum: 0.9
display: 50
max_iter: 200000
batch_size: 10
test_interval: 50
topk: 3
base_lr: 0.00004
start_iters: 0
best_model: 12345678.9
#-------------lr_policy--------------------#
# step
lr_policy: 'step'
policy_parameter:
  gamma: 0.333
  step_size: 25000
  #53100
# exp
# lr_policy: 'exp'
# policy_parameter:
#   gamma: 0.99
# 
# inv
# lr_policy: 'inv'
# policy_parameter:
#   gamma: 0.1
#   power: 0.1
# 
# multistep
#lr_policy: 'multistep'
#policy_parameter:
 # stepvalue: #[20000, 35000, 45000]
 # gamma: 0.33#0.1
# 
# poly
#lr_policy: 'poly'
#policy_parameter:
  #power: 1.5
  #max_iter: 250000
# 
# sigmoid
# lr_policy: 'sigmoid'
# policy_parameter:
#   gamma: 0.9
#   stepsize: 5000
#lr_policy: 'multistep-poly'
#policy_parameter:
  #stepvalue: [12435, 24870, 37350, 49740]
  #max_iter: 62175
  #gamma: 0.333
  #power: 1.2
